.TH ANALYSIS 1 2026-3月 "" "analysis"
.SH NAME
analysis \- analysis(embedding.file,
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIanalysis(embedding.file,
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBembedding.file\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.analysis at embedding.R:line 59
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
