.TH ANNOTATION_WORKFLOW 1 2023-May "" "Register the virtual cell network modelling workflows"
.SH NAME
annotation_workflow \- annotation_workflow()
.SH SYNOPSIS
\fIannotation_workflow()\fR
.SH VALUE
.PP
this function has no return value
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.annotation_workflow at apps.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
