.TH ASSEMBLE_METABOLIC_GRAPH 1 2025-Jun "" "assemble_metabolic_graph"
.SH NAME
assemble_metabolic_graph \- assemble_metabolic_graph(app, context)
.SH SYNOPSIS
\fIassemble_metabolic_graph(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.assemble_metabolic_graph at assemble_metabolic_graph.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
