.TH BATCH_DIAMOND 1 2026-7月 "internal" "Batch DIAMOND BLASTP Search Against Enzyme Database"
.SH NAME
batch_diamond \- batch_diamond(source.dir, result.dir,
    <i>diamond</i> = 'Sys.which'('diamond'),
    <i>n.threads</i> = <span style='color: green;'>32</span>)
.SH SYNOPSIS
\fIbatch_diamond(source.dir, result.dir,
    <i>diamond</i> = 'Sys.which'('diamond'),
    <i>n.threads</i> = <span style='color: green;'>32</span>)\fR
.SH DESCRIPTION
.PP
A helper function that formats a local EC number reference database and
executes DIAMOND BLASTP in batch mode for all protein FASTA files in a
given source directory.
.PP
.SH OPTIONS
.PP
\fBsource.dir\fB \fR\- . 
.PP
.PP
\fBresult.dir\fB \fR\- . 
.PP
.PP
\fBdiamond\fB \fR\- 'Sys.which'('diamond'). A character string specifying the file path to the DIAMOND
executable. Defaults to \code{Sys.which("diamond")}.
.PP
.PP
\fBn.threads\fB \fR\- 32. 
.PP
.SH VALUE
.PP
\code{invisible(NULL)}. This function is called for its side effects
of creating DIAMOND database files and BLASTP alignment output files
(\code{.m8}) in the \code{result_dir}.
.PP
.SH DETAILS
.PP
This function temporarily changes the working directory to \code{result_dir}
for the DIAMOND database creation and search operations, then restores the
original working directory upon completion.
The EC number reference database (\code{ec_numbers.fasta}) is sourced from
the package's built-in data directory. A DIAMOND database is created
on-the-fly before running the BLASTP searches.
For each \code{.faa} file found in \code{source_dir}, a corresponding
\code{.m8} alignment result file is generated in \code{result_dir}.
.PP
.SH EXAMPLES
.PP
#\dontrun{

# Run batch DIAMOND BLASTP on all .faa files
batch_diamond(
source_dir = "data/proteins",
result_dir = "results/diamond",
diamond = "/usr/bin/diamond",
n_threads = 16
)

#}
.PP
.SH SEE ALSO
\code{\link{make_diamond_hits}} for the main DIAMOND workflow step,
\code{\link{make_diamond}} for building individual reference databases.
.SH FILES
.PP
SMRUCC/R#.declare_function.batch_diamond at batch_diamond.R:line 48
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
