.TH BUILD_PROJECT 1 2026-4月 "" "build_project"
.SH NAME
build_project \- build_project(app, context)
.SH SYNOPSIS
\fIbuild_project(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.build_project at build_project.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
