.TH CHECK_BUILD_MODULE 1 2026-4月 "" "check_build_module"
.SH NAME
check_build_module \- check_build_module(flag)
.SH SYNOPSIS
\fIcheck_build_module(flag)\fR
.SH OPTIONS
.PP
\fBflag\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_build_module at apps.R:line 20
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
