.TH COMPILE_GENBANK 1 2024-Nov "" "Compile the virtual cell model from ncbi genbank file"
.SH NAME
compile_genbank \- compile_genbank(cad.registry, gbff)
.SH SYNOPSIS
\fIcompile_genbank(cad.registry, gbff)\fR
.SH OPTIONS
.PP
\fBcad.registry\fB \fR\- . 
.PP
.PP
\fBgbff\fB \fR\- . the file path to the template ncbi genbank file
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.compile_genbank at compiler.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
