.TH DIAMOND_BATCH 1 2026-7月 "" "diamond_batch"
.SH NAME
diamond_batch \- diamond_batch(diamond.blastp, diamond, temp.dir)
.SH SYNOPSIS
\fIdiamond_batch(diamond.blastp, diamond, temp.dir)\fR
.SH OPTIONS
.PP
\fBdiamond.blastp\fB \fR\- . 
.PP
.PP
\fBdiamond\fB \fR\- . 
.PP
.PP
\fBtemp.dir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.diamond_batch at make_diamond_hits.R:line 101
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
