.TH DIAMOND_EMBEDDING 1 2026-5月 "" "diamond_embedding"
.SH NAME
diamond_embedding \- diamond_embedding(diamond.result,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>union.contigs</i> = <span style='color: green;'>250</span>)
.SH SYNOPSIS
\fIdiamond_embedding(diamond.result,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>union.contigs</i> = <span style='color: green;'>250</span>)\fR
.SH OPTIONS
.PP
\fBdiamond.result\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBunion.contigs\fB \fR\- 250. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.diamond_embedding at embedding.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
