.TH EXPORT_TREE 1 2026-4月 "" "export_tree"
.SH NAME
export_tree \- export_tree(embedding.file,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>node.equals</i> = <span style='color: green;'>0.999</span>)
.SH SYNOPSIS
\fIexport_tree(embedding.file,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>node.equals</i> = <span style='color: green;'>0.999</span>)\fR
.SH OPTIONS
.PP
\fBembedding.file\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBnode.equals\fB \fR\- 0.999. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_tree at tree_viz.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
