.TH EXTRACT_GBFF 1 2025-Apr "" "Helper function for extract the annotation features from genbank file"
.SH NAME
extract_gbff \- extract_gbff(src,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>upstream.size</i> = <span style='color: green;'>150</span>,
    <i>tag.genbank.accid</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>verbose</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIextract_gbff(src,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>upstream.size</i> = <span style='color: green;'>150</span>,
    <i>tag.genbank.accid</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>verbose</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBsrc\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBupstream.size\fB \fR\- 150. 
.PP
.PP
\fBtag.genbank.accid\fB \fR\- FALSE. 
.PP
.PP
\fBverbose\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.extract_gbff at extract_gbff.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
