.TH EXTRACT_GENE_TABLE 1 2023-May "" "Extract the genbank source"
.SH NAME
extract_gene_table \- extract_gene_table(app, context)
.SH SYNOPSIS
\fIextract_gene_table(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the current workflow app object
.PP
.PP
\fBcontext\fB \fR\- . the workflow context object
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.extract_gene_table at extract_gene_table.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
