.TH GENOME_SCATTER_VIZ 1 2026-3月 "" "genome_scatter_viz"
.SH NAME
genome_scatter_viz \- genome_scatter_viz(data,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIgenome_scatter_viz(data,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.genome_scatter_viz at embedding.R:line 85
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
