.TH LOCAL_PROTDB 1 2025-Jul "" "Create local fasta database for protein alignment"
.SH NAME
local_protDb \- local_protDb(cad.registry, dbfile)
.SH SYNOPSIS
\fIlocal_protDb(cad.registry, dbfile)\fR
.SH OPTIONS
.PP
\fBcad.registry\fB \fR\- . 
.PP
.PP
\fBdbfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.local_protDb at local_protDb.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
