.TH MAGS_MODEL 1 2026-6月 "" "Compile the MAGs as virtual cell model"
.SH NAME
MAGs_model \- MAGs_model(contigs, tax.str,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIMAGs_model(contigs, tax.str,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBcontigs\fB \fR\- . a collection of the MAGs contigs assembly
.PP
.PP
\fBtax.str\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.MAGs_model at MAGs_model.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
