.TH MAKE_TERMS 1 2026-4月 "" "make_terms"
.SH NAME
make_terms \- make_terms(app, context)
.SH SYNOPSIS
\fImake_terms(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_terms at make_terms.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
