.TH MAKE_DIAMOND 1 2026-4月 "" "make_diamond"
.SH NAME
make_diamond \- make_diamond(local.db,
    <i>diamond</i> = 'Sys.which'('diamond'))
.SH SYNOPSIS
\fImake_diamond(local.db,
    <i>diamond</i> = 'Sys.which'('diamond'))\fR
.SH OPTIONS
.PP
\fBlocal.db\fB \fR\- . 
.PP
.PP
\fBdiamond\fB \fR\- 'Sys.which'('diamond'). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_diamond at make_diamond_hits.R:line 30
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
