.TH MAKE_TRN 1 2026-4月 "" "make_TRN"
.SH NAME
make_TRN \- make_TRN(app, context)
.SH SYNOPSIS
\fImake_TRN(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_TRN at make_TRN.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
