.TH MAKE_GENBANK_PROJ 1 2026-4月 "" "Extract the genbank source"
.SH NAME
make_genbank_proj \- make_genbank_proj(app, context)
.SH SYNOPSIS
\fImake_genbank_proj(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . the current workflow app object
.PP
.PP
\fBcontext\fB \fR\- . the workflow context object
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_genbank_proj at make_genbank_proj.R:line 10
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
