.TH MAKE_DIAMOND_HITS 1 2026-4月 "" "make_diamond_hits"
.SH NAME
make_diamond_hits \- make_diamond_hits(app, context)
.SH SYNOPSIS
\fImake_diamond_hits(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.make_diamond_hits at make_diamond_hits.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
