.TH METATRAITS 1 2026-6月 "" "metaTraits"
.SH NAME
metaTraits \- metaTraits(diamond)
.SH SYNOPSIS
\fImetaTraits(diamond)\fR
.SH OPTIONS
.PP
\fBdiamond\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metaTraits at metaTraits.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
