.TH MODELLING_CELLGRAPH 1 2023-Apr "" "Run the cell graph structure modelling workflow"
.SH NAME
modelling_cellgraph \- modelling_cellgraph(src,
    <i>outputdir</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fImodelling_cellgraph(src,
    <i>outputdir</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBsrc\fB \fR\- . the ncbi genbank assembly source file its file path
.PP
.PP
\fBoutputdir\fB \fR\- NULL. the result outputdir and temp workspace location, default value is NULL means use the parent dir of the input src
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.modelling_cellgraph at main.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
