.TH MODELLING_KINETICS 1 2023-Apr "" "Run the kinetics parameter fitting based on the omics expression data"
.SH NAME
modelling_kinetics \- modelling_kinetics(src,
    <i>outputdir</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fImodelling_kinetics(src,
    <i>outputdir</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBsrc\fB \fR\- . the GCModeller virtual cell model assembly file its file path
.PP
.PP
\fBoutputdir\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.modelling_kinetics at main.R:line 33
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
