.TH OPEN_CADLAB 1 2025-Jul "" "open_cadlab"
.SH NAME
open_cadlab \- open_cadlab(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>)
.SH SYNOPSIS
\fIopen_cadlab(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>)\fR
.SH OPTIONS
.PP
\fBuser\fB \fR\- . 
.PP
.PP
\fBpasswd\fB \fR\- . 
.PP
.PP
\fBhost\fB \fR\- 'localhost'. 
.PP
.PP
\fBport\fB \fR\- 3306. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.open_cadlab at open.R:line 18
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
