.TH OPEN_REGISTRY 1 2025-Apr "" "open mysql connection to the cad registry"
.SH NAME
open_registry \- open_registry(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>)
.SH SYNOPSIS
\fIopen_registry(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>)\fR
.SH OPTIONS
.PP
\fBuser\fB \fR\- . 
.PP
.PP
\fBpasswd\fB \fR\- . 
.PP
.PP
\fBhost\fB \fR\- 'localhost'. 
.PP
.PP
\fBport\fB \fR\- 3306. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.open_registry at open.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
