.TH PAIRWISE_BUILDER 1 2026-7月 "" "pairwise_builder"
.SH NAME
pairwise_builder \- pairwise_builder(proj.dir)
.SH SYNOPSIS
\fIpairwise_builder(proj.dir)\fR
.SH OPTIONS
.PP
\fBproj.dir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pairwise_builder at pairwise_builder.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
