.TH PANGENOME 1 2026-4月 "" "pan-genome analysis of the microbial community"
.SH NAME
pangenome \- pangenome(src, result.dir)
.SH SYNOPSIS
\fIpangenome(src, result.dir)\fR
.SH OPTIONS
.PP
\fBsrc\fB \fR\- . a character vector of the directory path that contains the ncbi genbank assembly files.
.PP
.PP
\fBresult.dir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pangenome at pangenome.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
