.TH PFAM_DIAMOND 1 2026-5月 "" "pfam_diamond"
.SH NAME
pfam_diamond \- pfam_diamond(proteins,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>diamond</i> = 'Sys.which'('diamond'))
.SH SYNOPSIS
\fIpfam_diamond(proteins,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>diamond</i> = 'Sys.which'('diamond'))\fR
.SH OPTIONS
.PP
\fBproteins\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.PP
\fBdiamond\fB \fR\- 'Sys.which'('diamond'). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pfam_diamond at pfam.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
