.TH REACTION_POOL 1 2025-Apr "" "pull reaction data from cad registry to local"
.SH NAME
reaction_pool \- reaction_pool(cad.registry, repo)
.SH SYNOPSIS
\fIreaction_pool(cad.registry, repo)\fR
.SH OPTIONS
.PP
\fBcad.registry\fB \fR\- . 
.PP
.PP
\fBrepo\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.reaction_pool at reaction_pool.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
