.TH RUN_WORKFLOW 1 2023-Apr "" "Run the modelling workflow"
.SH NAME
run_workflow \- run_workflow(src,
    <i>outputdir</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIrun_workflow(src,
    <i>outputdir</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBsrc\fB \fR\- . the ncbi genbank assembly source file its file path
.PP
.PP
\fBoutputdir\fB \fR\- NULL. the result outputdir and temp workspace location, default value is NULL means use the parent dir of the input src
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.run_workflow at main.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
