.TH SCAN_TFBS_BATCH 1 2026-7月 "" "scan_tfbs_batch"
.SH NAME
scan_tfbs_batch \- scan_tfbs_batch(motifs.db,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>motif.pvalcut</i> = <span style='color: green;'>1E-06</span>)
.SH SYNOPSIS
\fIscan_tfbs_batch(motifs.db,
    <i>n.threads</i> = <span style='color: green;'>8</span>,
    <i>motif.pvalcut</i> = <span style='color: green;'>1E-06</span>)\fR
.SH OPTIONS
.PP
\fBmotifs.db\fB \fR\- . 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.PP
\fBmotif.pvalcut\fB \fR\- 1E-06. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.scan_tfbs_batch at tfbs_motif_scanning.R:line 102
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
