.TH SEQUENTIAL_BATCH 1 2026-7月 "" "sequential_batch"
.SH NAME
sequential_batch \- sequential_batch(src,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>args</i> = 'list'())
.SH SYNOPSIS
\fIsequential_batch(src,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>args</i> = 'list'())\fR
.SH OPTIONS
.PP
\fBsrc\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.PP
\fBargs\fB \fR\- 'list'(). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.sequential_batch at sequential_batch.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
