.TH SINGLECELLS_ANALYSIS 1 2026-5月 "" "singlecells_analysis"
.SH NAME
singlecells_analysis \- singlecells_analysis(embedding.file,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIsinglecells_analysis(embedding.file,
    <i>workdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBembedding.file\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.singlecells_analysis at singlecells.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
