.TH SINGLECELLS_VIZ 1 2026-5月 "" "singlecells_viz"
.SH NAME
singlecells_viz \- singlecells_viz(rawdata,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIsinglecells_viz(rawdata,
    <i>outputdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBrawdata\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.singlecells_viz at singlecells_viz.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
