.TH TFBS_MOTIF_SCANNING 1 2025-Jul "" "tfbs_motif_scanning"
.SH NAME
tfbs_motif_scanning \- tfbs_motif_scanning(app, context)
.SH SYNOPSIS
\fItfbs_motif_scanning(app, context)\fR
.SH OPTIONS
.PP
\fBapp\fB \fR\- . 
.PP
.PP
\fBcontext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.tfbs_motif_scanning at tfbs_motif_scanning.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
