.TH WORKFLOW_REGISTRY 1 2023-Apr "" "workflow_registry"
.SH NAME
workflow_registry \- workflow_registry()
.SH SYNOPSIS
\fIworkflow_registry()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.workflow_registry at apps.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
