.\" man page create by R# package system.
.TH BUILDER 1 2000-Jan "create_modelfile" "create_modelfile"
.SH NAME
create_modelfile \- 
.SH SYNOPSIS
\fIcreate_modelfile(\fBregister\fR as <generic> biocad_registry, 
\fBgenes\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Builder
.SH FILES
.PP
CellRender.dll
.PP
