.\" man page create by R# package system.
.TH PROJECT 1 2000-1月 "build" "build"
.SH NAME
build \- build the genbank project as a virtual cell model
.SH SYNOPSIS
\fIbuild(\fBproj\fR as <generic> GenBankProject, 
\fBdatapool\fR as <generic> DataRepository, 
\fBvcell_name\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
build the genbank project as a virtual cell model
.PP
.SH OPTIONS
.PP
\fBproj\fB \fR\- -. 
.PP
.PP
\fBdatapool\fB \fR\- -. 
.PP
.PP
\fBvcell_name\fB \fR\- -. 
.PP
.SH SEE ALSO
project
.SH FILES
.PP
CellRender.dll
.PP
