.\" man page create by R# package system.
.TH PROJECT 1 2000-1月 "new" "new"
.SH NAME
new \- 
.SH SYNOPSIS
\fInew(\fBreplicons\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBreplicons\fB \fR\- a vector of the ncbi genbank object of the genome replicons. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
project
.SH FILES
.PP
CellRender.dll
.PP
