.\" man page create by R# package system.
.TH WORKFLOW 1 2000-1月 "enzyme_table" "enzyme_table"
.SH NAME
enzyme_table \- get enzyme annotation result table from the project model
.SH SYNOPSIS
\fIenzyme_table(\fBproj\fR as <generic> GenBankProject);\fR
.SH DESCRIPTION
.PP
get enzyme annotation result table from the project model
.PP
.SH OPTIONS
.PP
\fBproj\fB \fR\- -. 
.PP
.SH SEE ALSO
workflow
.SH FILES
.PP
CellRender.dll
.PP
