.\" man page create by R# package system.
.TH WORKFLOW 1 2000-1月 "gene_table" "gene_table"
.SH NAME
gene_table \- extract the gene table from the project model.
.SH SYNOPSIS
\fIgene_table(\fBproj\fR as <generic> GenBankProject);\fR
.SH DESCRIPTION
.PP
extract the gene table from the project model.
.PP
.SH OPTIONS
.PP
\fBproj\fB \fR\- -. 
.PP
.SH SEE ALSO
workflow
.SH FILES
.PP
CellRender.dll
.PP
