.\" man page create by R# package system.
.TH WORKFLOW 1 2000-1月 "set_traits" "set_traits"
.SH NAME
set_traits \- 
.SH SYNOPSIS
\fIset_traits(\fBproj\fR as <generic> GenBankProject, 
\fBtraits\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBproj\fB \fR\- -. 
.PP
.PP
\fBtraits\fB \fR\- the phenotype annotation @\fBT:SMRUCC.genomics.Analysis.Metagenome.MetaFunction.metaTraits.Traitar.ReportJSON\fR result data.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
workflow
.SH FILES
.PP
CellRender.dll
.PP
