.\" man page create by R# package system.
.TH WORKFLOW 1 2000-1月 "tss_upstream" "tss_upstream"
.SH NAME
tss_upstream \- extract of the tss upstream location site sequence data
.SH SYNOPSIS
\fItss_upstream(\fBproj\fR as <generic> GenBankProject);\fR
.SH DESCRIPTION
.PP
extract of the tss upstream location site sequence data
.PP
.SH OPTIONS
.PP
\fBproj\fB \fR\- -. 
.PP
.SH SEE ALSO
workflow
.SH FILES
.PP
CellRender.dll
.PP
