.\" man page create by R# package system.
.TH MODELS 1 2000-Jan "enzyme_function" "enzyme_function"
.SH NAME
enzyme_function \- 
.SH SYNOPSIS
\fIenzyme_function(\fBbiocad_registry\fR as <generic> biocad_registry, 
\fBenzyme_id\fR as string, 
\fBec_number\fR as string, 
\fBmetabolites\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
