.\" man page create by R# package system.
.TH MODELS 1 2000-Jan "subcellular_location" "subcellular_location"
.SH NAME
subcellular_location \- 
.SH SYNOPSIS
\fIsubcellular_location(\fBbiocad_registry\fR as <generic> biocad_registry, 
\fBname\fR as string, 
\fBtopology\fR as string);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
