.\" man page create by R# package system.
.TH MODELS 1 2000-Jan "vocabulary_id" "vocabulary_id"
.SH NAME
vocabulary_id \- 
.SH SYNOPSIS
\fIvocabulary_id(\fBbiocad_registry\fR as <generic> biocad_registry, 
\fBterm\fR as string, 
\fBcategory\fR as string, 
\fBdesc\fR as string = "");\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
